export enum AdminEnum {
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  ORGANIZATION_ADMIN = 'ORGANIZATION_ADMIN',
  CLIENT_ADMIN = 'CLIENT_ADMIN',
  ORGANIZATION_USER = 'ORGANIZATION_USER',
  CLIENT_USER = 'CLIENT_USER'
}
